# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 12:06:03 2017

@author: k26609
"""

addr_map_direction = {'N':'NORTH',
                      'N.':'NORTH',
                      'S':'SOUTH',
                      'S.':'SOUTH',
                      'E':'EAST',
                      'E.':'EAST',
                      'W':'WEST',
                      'W.':'WEST',
                      'SW':'SOUTHWEST',
                      'SW.':'SOUTHWEST',
                      'NW':'NORTHWEST',
                      'NW.':'NORTHWEST',
                      'SE':'SOUTHEAST',
                      'SE.':'SOUTHEAST',
                      'NE':'NORTHEAST',
                      'NE.':'NORTHEAST'}

# reference 1: http://www.semaphorecorp.com/zp4/abbrev.html       
# reference 2: http://www.gis.co.clay.mn.us/usps.htm
addr_map_street = {	'ALY':'ALLEY',
					'ANX':'ANNEX',
					'APT':'APARTMENT',
					'ARC':'ARCADE',
					'AVE':'AVENUE',
					'BSMT':'BASEMENT',
					'BYU':'BAYOU',
					'BCH':'BEACH',
					'BND':'BEND',
					'BLF':'BLUFF',
					'BTM':'BOTTOM',
					'BLVD':'BOULEVARD',
					'BR':'BRANCH',
					'BRG':'BRIDGE',
					'BRK':'BROOK',
					'BLDG':'BUILDING',
					'BG':'BURG',
					'BYP':'BYPASS',
					'CP':'CAMP',
					'CYN':'CANYON',
					'CPE':'CAPE',
					'CSWY':'CAUSEWAY',
					'CTR':'CENTER',
					'CIR':'CIRCLE',
					'CLFS':'CLIFF',
#					'CLFS':'CLIFFS',
					'CLB':'CLUB',
					'COR':'CORNER',
					'CORS':'CORNERS',
					'CRSE':'COURSE',
					'CT':'COURT',
					'CTS':'COURTS',
					'CV':'COVE',
					'CRK':'CREEK',
					'CRES':'CRESCENT',
					'XING':'CROSSING',
					'DL':'DALE',
					'DM':'DAM',
					'DEPT':'DEPARTMENT',
					'DV':'DIVIDE',
					'DR':'DRIVE',
					'EST':'ESTATE',
					'EXPY':'EXPRESSWAY',
					'EXT':'EXTENSION',
					'FLS':'FALLS',
					'FRY':'FERRY',
					'FLD':'FIELD',
					'FLDS':'FIELDS',
					'FLT':'FLAT',
					'FL':'FLOOR',
					'FRD':'FORD',
					'FRST':'FOREST',
					'FRG':'FORGE',
					'FRK':'FORK',
					'FRKS':'FORKS',
					'FT':'FORT',
					'FWY':'FREEWAY',
					'FRNT':'FRONT',
					'GDNS':'GARDEN',
#					'GDNS':'GARDENS',
					'GTWY':'GATEWAY',
					'GLN':'GLEN',
					'GRN':'GREEN',
					'GRV':'GROVE',
					'HNGR':'HANGER',
					'HBR':'HARBOR',
					'HVN':'HAVEN',
					'HTS':'HEIGHTS',
					'HWY':'HIGHWAY',
					'HL':'HILL',
					'HLS':'HILLS',
					'HOLW':'HOLLOW',
					'INLT':'INLET',
					'IS':'ISLAND',
					'ISS':'ISLANDS',
					'JCT':'JUNCTION',
					'KY':'KEY',
					'KNLS':'KNOLL',
#					'KNLS':'KNOLLS',
					'LK':'LAKE',
					'LKS':'LAKES',
					'LNDG':'LANDING',
					'LN':'LANE',
					'LGT':'LIGHT',
					'LF':'LOAF',
					'LBBY':'LOBBY',
					'LCKS':'LOCK',
#					'LCKS':'LOCKS',
					'LDG':'LODGE',
					'LOWR':'LOWER',
					'MNR':'MANOR',
					'MDWS':'MEADOW',
#					'MDWS':'MEADOWS',
					'ML':'MILL',
					'MLS':'MILLS',
					'MSN':'MISSION',
					'MT':'MOUNT',
					'MTN':'MOUNTAIN',
					'NCK':'NECK',
					'OFC':'OFFICE',
					'ORCH':'ORCHARD',
					'PKWY':'PARKWAY',
					'PH':'PENTHOUSE',
					'PNES':'PINE',
#					'PNES':'PINES',
					'PL':'PLACE',
					'PLN':'PLAIN',
					'PLNS':'PLAINS',
					'PLZ':'PLAZA',
					'PT':'POINT',
					'PRT':'PORT',
					'PR':'PRAIRIE',
					'RADL':'RADIAL',
					'RNCH':'RANCH',
					'RPDS':'RAPID',
#					'RPDS':'RAPIDS',
					'RST':'REST',
					'RDG':'RIDGE',
					'RIV':'RIVER',
					'RD':'ROAD',
					'RM':'ROOM',
					'SHL':'SHOAL',
					'SHLS':'SHOALS',
					'SHR':'SHORE',
					'SHRS':'SHORES',
					'SPC':'SPACE',
					'SPG':'SPRING',
					'SPGS':'SPRINGS',
					'SQ':'SQUARE',
					'STA':'STATION',
					'STRA':'STRAVENUE',
					'STRM':'STREAM',
					'ST':'STREET',
					'STE':'SUITE',
					'SMT':'SUMMIT',
					'TER':'TERRACE',
					'TRCE':'TRACE',
					'TRAK':'TRACK',
					'TRFY':'TRAFFICWAY',
					'TRL':'TRAIL',
					'TRLR':'TRAILER',
					'TUNL':'TUNNEL',
					'TPKE':'TURNPIKE',
					'UN':'UNION',
					'UPPR':'UPPER',
					'VLY':'VALLEY',
					'VIA':'VIADUCT',
					'VW':'VIEW',
					'VLG':'VILLAGE',
					'VL':'VILLE',
					'VIS':'VISTA',
					'WAY':'WAY',
					'WLS':'WELL',
#					'WLS':'WELLS'
                }

#http://www.gis.co.clay.mn.us/USPS.htm#secunitdesig
addr_map_unit = {'APT':'APARTMENT',
                'BSMT':'BASEMENT',
                'BLDG':'BUILDING',
                'DEPT':'DEPARTMENT',
                'FL':'FLOOR',
                'FRNT':'FRONT',
                'HNGR':'HANGAR',
                'LBBY':'LOBBY',
                'LOT':'LOT',
                'LOWR':'LOWER',
                'OFC':'OFFICE',
                'PH':'PENTHOUSE',
                'PIER':'PIER',
                'REAR':'REAR',
                'RM':'ROOM',
                'SIDE':'SIDE',
                'SLIP':'SLIP',
                'SPC':'SPACE',
                'STOP':'STOP',
                'STE':'SUITE',
                'TRLR':'TRAILER',
                'UNIT':'UNIT',
                'UPPR':'UPPER'
                }

#reference: http://www.worldatlas.com/aatlas/ctycodes.htm
addr_map_country = {'US':'US',
                    'AFGHANISTAN':'AF',
                    'ALBANIA':'AL',
                    'ALGERIA':'DZ',
                    'AMERICAN SAMOA':'AS',
                    'ANDORRA':'AD',
                    'ANGOLA':'AO',
                    'ANGUILLA':'AI',
                    'ANTARCTICA':'AQ',
                    'ANTIGUA AND BARBUDA':'AG',
                    'ARGENTINA':'AR',
                    'ARMENIA':'AM',
                    'ARUBA':'AW',
                    'AUSTRALIA':'AU',
                    'AUSTRIA':'AT',
                    'AZERBAIJAN':'AZ',
                    'BAHAMAS':'BS',
                    'BAHRAIN':'BH',
                    'BANGLADESH':'BD',
                    'BARBADOS':'BB',
                    'BELARUS':'BY',
                    'BELGIUM':'BE',
                    'BELIZE':'BZ',
                    'BENIN':'BJ',
                    'BERMUDA':'BM',
                    'BHUTAN':'BT',
                    'BOLIVIA':'BO',
                    'BONAIRE':'BQ',
                    'BOSNIA AND HERZEGOVINA':'BA',
                    'BOTSWANA':'BW',
                    'BOUVET ISLAND':'BV',
                    'BRAZIL':'BR',
                    'BRITISH INDIAN OCEAN TERRITORY':'IO',
                    'BRUNEI DARUSSALAM':'BN',
                    'BULGARIA':'BG',
                    'BURKINA FASO':'BF',
                    'BURUNDI':'BI',
                    'CAMBODIA':'KH',
                    'CAMEROON':'CM',
                    'CANADA':'CA',
                    'CAPE VERDE':'CV',
                    'CAYMAN ISLANDS':'KY',
                    'CENTRAL AFRICAN REPUBLIC':'CF',
                    'CHAD':'TD',
                    'CHILE':'CL',
                    'CHINA':'CN',
                    'CHRISTMAS ISLAND':'CX',
                    'COCOS (KEELING) ISLANDS':'CC',
                    'COLOMBIA':'CO',
                    'COMOROS':'KM',
                    'CONGO':'CG',
                    'DEMOCRATIC REPUBLIC OF THE CONGO':'CD',
                    'COOK ISLANDS':'CK',
                    'COSTA RICA':'CR',
                    'CROATIA':'HR',
                    'CUBA':'CU',
                    'CURACAO':'CW',
                    'CYPRUS':'CY',
                    'CZECH REPUBLIC':'CZ',
                    'COTE D\'IVOIRE':'CI',
                    'DENMARK':'DK',
                    'DJIBOUTI':'DJ',
                    'DOMINICA':'DM',
                    'DOMINICAN REPUBLIC':'DO',
                    'ECUADOR':'EC',
                    'EGYPT':'EG',
                    'EL SALVADOR':'SV',
                    'EQUATORIAL GUINEA':'GQ',
                    'ERITREA':'ER',
                    'ESTONIA':'EE',
                    'ETHIOPIA':'ET',
                    'FALKLAND ISLANDS (MALVINAS)':'FK',
                    'FAROE ISLANDS':'FO',
                    'FIJI':'FJ',
                    'FINLAND':'FI',
                    'FRANCE':'FR',
                    'FRENCH GUIANA':'GF',
                    'FRENCH POLYNESIA':'PF',
                    'FRENCH SOUTHERN TERRITORIES':'TF',
                    'GABON':'GA',
                    'GAMBIA':'GM',
                    'GEORGIA':'GE',
                    'GERMANY':'DE',
                    'GHANA':'GH',
                    'GIBRALTAR':'GI',
                    'GREECE':'GR',
                    'GREENLAND':'GL',
                    'GRENADA':'GD',
                    'GUADELOUPE':'GP',
                    'GUAM':'GU',
                    'GUATEMALA':'GT',
                    'GUERNSEY':'GG',
                    'GUINEA':'GN',
                    'GUINEA-BISSAU':'GW',
                    'GUYANA':'GY',
                    'HAITI':'HT',
                    'HEARD ISLAND AND MCDONALD MCDONALD ISLANDS':'HM',
                    'HOLY SEE (VATICAN CITY STATE)':'VA',
                    'HONDURAS':'HN',
                    'HONG KONG':'HK',
                    'HUNGARY':'HU',
                    'ICELAND':'IS',
                    'INDIA':'IN',
                    'INDONESIA':'ID',
                    'IRAN, ISLAMIC REPUBLIC OF':'IR',
                    'IRAQ':'IQ',
                    'IRELAND':'IE',
                    'ISLE OF MAN':'IM',
                    'ISRAEL':'IL',
                    'ITALY':'IT',
                    'JAMAICA':'JM',
                    'JAPAN':'JP',
                    'JERSEY':'JE',
                    'JORDAN':'JO',
                    'KAZAKHSTAN':'KZ',
                    'KENYA':'KE',
                    'KIRIBATI':'KI',
                    'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF':'KP',
                    'KOREA, REPUBLIC OF':'KR',
                    'KUWAIT':'KW',
                    'KYRGYZSTAN':'KG',
                    'LAO PEOPLE\'S DEMOCRATIC REPUBLIC':'LA',
                    'LATVIA':'LV',
                    'LEBANON':'LB',
                    'LESOTHO':'LS',
                    'LIBERIA':'LR',
                    'LIBYA':'LY',
                    'LIECHTENSTEIN':'LI',
                    'LITHUANIA':'LT',
                    'LUXEMBOURG':'LU',
                    'MACAO':'MO',
                    'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF':'MK',
                    'MADAGASCAR':'MG',
                    'MALAWI':'MW',
                    'MALAYSIA':'MY',
                    'MALDIVES':'MV',
                    'MALI':'ML',
                    'MALTA':'MT',
                    'MARSHALL ISLANDS':'MH',
                    'MARTINIQUE':'MQ',
                    'MAURITANIA':'MR',
                    'MAURITIUS':'MU',
                    'MAYOTTE':'YT',
                    'MEXICO':'MX',
                    'MICRONESIA, FEDERATED STATES OF':'FM',
                    'MOLDOVA, REPUBLIC OF':'MD',
                    'MONACO':'MC',
                    'MONGOLIA':'MN',
                    'MONTENEGRO':'ME',
                    'MONTSERRAT':'MS',
                    'MOROCCO':'MA',
                    'MOZAMBIQUE':'MZ',
                    'MYANMAR':'MM',
                    'NAMIBIA':'NA',
                    'NAURU':'NR',
                    'NEPAL':'NP',
                    'NETHERLANDS':'NL',
                    'NEW CALEDONIA':'NC',
                    'NEW ZEALAND':'NZ',
                    'NICARAGUA':'NI',
                    'NIGER':'NE',
                    'NIGERIA':'NG',
                    'NIUE':'NU',
                    'NORFOLK ISLAND':'NF',
                    'NORTHERN MARIANA ISLANDS':'MP',
                    'NORWAY':'NO',
                    'OMAN':'OM',
                    'PAKISTAN':'PK',
                    'PALAU':'PW',
                    'PALESTINE, STATE OF':'PS',
                    'PANAMA':'PA',
                    'PAPUA NEW GUINEA':'PG',
                    'PARAGUAY':'PY',
                    'PERU':'PE',
                    'PHILIPPINES':'PH',
                    'PITCAIRN':'PN',
                    'POLAND':'PL',
                    'PORTUGAL':'PT',
                    'PUERTO RICO':'PR',
                    'QATAR':'QA',
                    'ROMANIA':'RO',
                    'RUSSIAN FEDERATION':'RU',
                    'RWANDA':'RW',
                    'REUNION':'RE',
                    'SAINT BARTHELEMY':'BL',
                    'SAINT HELENA':'SH',
                    'SAINT KITTS AND NEVIS':'KN',
                    'SAINT LUCIA':'LC',
                    'SAINT MARTIN (FRENCH PART)':'MF',
                    'SAINT PIERRE AND MIQUELON':'PM',
                    'SAINT VINCENT AND THE GRENADINES':'VC',
                    'SAMOA':'WS',
                    'SAN MARINO':'SM',
                    'SAO TOME AND PRINCIPE':'ST',
                    'SAUDI ARABIA':'SA',
                    'SENEGAL':'SN',
                    'SERBIA':'RS',
                    'SEYCHELLES':'SC',
                    'SIERRA LEONE':'SL',
                    'SINGAPORE':'SG',
                    'SINT MAARTEN (DUTCH PART)':'SX',
                    'SLOVAKIA':'SK',
                    'SLOVENIA':'SI',
                    'SOLOMON ISLANDS':'SB',
                    'SOMALIA':'SO',
                    'SOUTH AFRICA':'ZA',
                    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS':'GS',
                    'SOUTH SUDAN':'SS',
                    'SPAIN':'ES',
                    'SRI LANKA':'LK',
                    'SUDAN':'SD',
                    'SURINAME':'SR',
                    'SVALBARD AND JAN MAYEN':'SJ',
                    'SWAZILAND':'SZ',
                    'SWEDEN':'SE',
                    'SWITZERLAND':'CH',
                    'SYRIAN ARAB REPUBLIC':'SY',
                    'TAIWAN, PROVINCE OF CHINA':'TW',
                    'TAJIKISTAN':'TJ',
                    'UNITED REPUBLIC OF TANZANIA':'TZ',
                    'THAILAND':'TH',
                    'TIMOR-LESTE':'TL',
                    'TOGO':'TG',
                    'TOKELAU':'TK',
                    'TONGA':'TO',
                    'TRINIDAD AND TOBAGO':'TT',
                    'TUNISIA':'TN',
                    'TURKEY':'TR',
                    'TURKMENISTAN':'TM',
                    'TURKS AND CAICOS ISLANDS':'TC',
                    'TUVALU':'TV',
                    'UGANDA':'UG',
                    'UKRAINE':'UA',
                    'UNITED ARAB EMIRATES':'AE',
                    'UNITED KINGDOM':'GB',
                    'UNITED STATES':'US',
                    'UNITED STATES MINOR OUTLYING ISLANDS':'UM',
                    'URUGUAY':'UY',
                    'UZBEKISTAN':'UZ',
                    'VANUATU':'VU',
                    'VENEZUELA':'VE',
                    'VIET NAM':'VN',
                    'BRITISH VIRGIN ISLANDS':'VG',
                    'US VIRGIN ISLANDS':'VI',
                    'WALLIS AND FUTUNA':'WF',
                    'WESTERN SAHARA':'EH',
                    'YEMEN':'YE',
                    'ZAMBIA':'ZM',
                    'ZIMBABWE':'ZW'
                    }